name: Deploy
description: 'composite run action'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

runs:
  using: "composite"
  steps:
    - name: Deploy
      shell: bash
      run: |
        echo I am deploying
