
runs:
  using: composite
  steps:
    - name: Sig pkg
      shell: bash
      run: |
        echo The var is "${{ inputs.var }}"
        env
        # echo "$GPG_KEY_B64"| base64 -d | gpg --batch --no-tty --allow-secret-key-import --import -
        # unset GPG_KEY_B64
        # export GPG_PASSPHRASE=$(echo $GPG_KEY_PASS_B64 | base64 -di)
        # unset GPG_KEY_PASS_B64
        # export GPG_KEYID=$(gpg --with-colon --list-secret-keys | head -n1 | cut -d : -f 5)
        # for PKG in $(ls *.deb); do
        #   ./sign.sh $PKG
        # done
