# this needs access to ${{secrets.SECRET_A}}
name: Sign packages
inputs:
  GPG_KEY_B64:
    description: key
    required: true
  GPG_KEY_PASS_B64:
    description: pass
    required: true
  SUPA_SECRET:
    description: pass
    required: true
runs:
  using: composite
  steps:
    - name: Sig pkg
      shell: bash
      run: |
        if [ ${KEY} = "butts" ]; then
          echo "We're in luck!"
        fi

        echo "${{ inputs.GPG_KEY_B64 }}"| base64 -d | gpg --batch --no-tty --allow-secret-key-import --import -
        export GPG_PASSPHRASE=$(echo ${{inputs.GPG_KEY_PASS_B64}} | base64 -di)
        export GPG_KEYID=$(gpg --with-colon --list-secret-keys | head -n1 | cut -d : -f 5)
        for PKG in $(ls *.deb); do
          .github/actions/sign/sign.sh $PKG
        done
