name: Package
description: 'composite run action'

runs:
  using: "composite"
  steps:
    - name: Download assets
      uses: actions/download-artifact@v3
      with:
        name: build_materials.txt

    - name: Build package
      shell: bash
      run: |
        echo "packaged" >> build_materials.txt
        mv build_materials.txt PACKAGE

    - name: Save assets
      uses: actions/upload-artifact@v3
      with:
        name: PACKAGE
