name: Muh secretions
inputs:
  GPG_KEY_B64:
    description: 'A Github PAT'
    required: true
  GPG_KEY_PASS_B64:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Using secretsssssss
      shell: bash
      env:
        GPG_KEY_B64: '${{ inputs.GPG_KEY_B64 }}'
        GPG_KEY_PASS_B64: '${{ inputs.GPG_KEY_PASS_B64 }}'
        sec: ${{ github.secrets }}
      run: |
        echo "Wth going on?"
        echo "secrets: ${sec}"
        echo "GPG_KEY_B64: ${GPG_KEY_B64}"
        echo "GPG_KEY_PASS_B64: ${GPG_KEY_PASS_B64}"
        env
