name: Muh secretions
inputs:
  GPG_KEY_B64:
    description: 'A Github PAT'
    required: true
  GPG_KEY_PASS_B64:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Using secretsssssss
      shell: bash
      env:
        GPG_KEY_B64: ${{ inputs.GPG_KEY_B64 }}
      run: |
        echo I am deploying ${GPG_KEY_B64}
