name: 🏗 Build

on: workflow_call

jobs:
  build_ubuntu:
    name: Ubuntu
    strategy:
      matrix:
        version: [20.04, 22.04]
        compiler: ['gcc', 'clang']
        build_type: ['release', 'debug']

    runs-on: ubuntu-${{ matrix.version}}
    steps:
      - uses: actions/checkout@v3
        name: Ubuntu ${{ matrix.version }}

      - uses: legleux/failure/.github/actions/ubuntu/build@main

      - uses: actions/upload-artifact@master
        with:
          name: executable
          path: ${{github.workspace}}

  test_ubuntu:
    strategy:
      matrix:
        version: [20.04, 22.04]
    runs-on: ubuntu-${{ matrix.version}}
    needs: build_ubuntu
    steps:
      - uses: legleux/failure/.github/actions/ubuntu/test@main
      - uses: actions/download-artifact@master
        with:
          name: executable
          path: ${{github.workspace}}

          # path: executable
      - run: cat executable

  # macOS:
  #   strategy:
  #     matrix:
  #       version: [macos-11, macos-12]
  #   runs-on: ${{ matrix.version}}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         os-version: ${{ matrix.version }}
