name: Package debs

on: workflow_call

jobs:
  package_deb:
    name: Build debian packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: ${{ github.workflow }}

      - uses: legleux/failure/.github/actions/deploy@main

      - uses: actions/upload-artifact@master
        with:
          name: executable
          path: ${{github.workspace}}
