name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.runner || 'ubuntu-20.04' }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - runner: ubuntu-20.04
            name: Ubuntu 20.04

          - runner: macos-11
            name: macOS 11

    steps:


      - name: Build
        run: |
          if [[ $RANDOM -lt 30000 ]] ; then return 0; else return 1; fi;
