name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.runner || 'ubuntu-20.04' }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - runner: ubuntu-20.04
            name: Ubuntu 20.04

          - runner: macos-11
            name: macOS 11

    steps:

      - name: Build
        run: |
          if [[ $RANDOM -lt $(echo "2^14" | bc) ]] ; then (exit 0); else (exit 1); fi;

      - name: Test
        if: always() && ${{ matrix.runner }} == 'ubuntu'
        run: echo "I are run"