name: CI
on:
  push:
    branches: main

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  ubuntu:
    name: Ubuntu
    uses: legleux/failure/.github/workflows/ubuntu.yml@main

  macos:
    name: macOS
    uses: legleux/failure/.github/workflows/macos.yml@main

  # test_ubuntu:
  #   needs: build_ubuntu
  #   uses: legleux/failure/.github/workflows/test_ubuntu.yml@main

  # test_macos:
  #   needs: build_macos
  #   uses: legleux/failure/.github/workflows/test_macos.yml@main
  deploy:
    name: Deploy
    needs: ['ubuntu', 'macos']
    uses: legleux/failure/.github/workflows/deploy.yml@main
