name: Sign packages
on: push

jobs:
  sign:
    name: Sign packages
    runs-on: ubuntu-20.04
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Install equivs
        run: sudo apt-get update && sudo apt-get install -y equivs
      - name: Write equivs file
        run: |
          cat  > a.equivs <<EOL
            Package: fake
            Version: 1.2.3
            Maintainer: Mee <support@me.com>
            Architecture: all
            Depends: butts
          EOL
          cat a.equivs
          equivs-build a.equivs
          ls -l
      - name: Sign the fucking package
        uses: legleux/failure/.github/actions/sign@main
