name: Sign packages
on: push

jobs:
  sign:
    name: Sign packages
    runs-on: ubuntu-20.04
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Install equivs
        run: sudo apt-get update && sudo apt-get install -y equivs
      - name: Write equivs file
        run: |
          cat  > a.equivs <<EOL
            Version: 666
            Maintainer: Mee <support@me.com>
            Architecture: all
          EOL
          equivs-build a.equivs
          ls -l
