name: Sign packages
on: push

jobs:
  sign:
    name: Sign packages
    runs-on: ubuntu-20.04
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Install equivs
        run: sudo apt-get update && sudo apt-get install -y equivs
      - name: Write equivs file
        run: |
          echo -en 'Package: fake\nVersion: 1.2.3\nMaintainer: Mee <support@me.com>\nArchitecture: all\nDepends: butts' > a.equivs
          cat a.equivs
          equivs-build a.equivs
          ls -lh

      - name: check we have the pacakge
        run: ls -lh

      - name: Sign the fucking package
        uses: legleux/failure/.github/actions/sign@main
